# Kubernetes Secret for DigitalOcean Managed Redis Credentials
# Phase 5 Component 4: Cloud Deployment
#
# IMPORTANT: This file contains placeholders for sensitive credentials.
# DO NOT commit actual credentials to version control.
#
# Usage:
#   1. Replace <PLACEHOLDER> values with actual DO Managed Redis credentials
#   2. Apply to cluster: kubectl apply -f redis-secret.yaml
#   3. Delete this file after applying (or use sealed-secrets for GitOps)
#
# Alternative (recommended): Create secret directly via kubectl
#   kubectl create secret generic redis-credentials \
#     --from-literal=redis-host="todo-app-redis-phase5-do-user-12345-0.db.ondigitalocean.com" \
#     --from-literal=redis-port="25061" \
#     --from-literal=redis-password="<generated-password>" \
#     --from-literal=redis-tls="true" \
#     --namespace default

apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: default
  labels:
    app: todo-app
    component: state-store
    environment: production
type: Opaque
stringData:
  # DigitalOcean Managed Redis hostname
  # Format: <cluster-name>-do-user-<id>-0.db.ondigitalocean.com
  # Get from: doctl databases connection <cluster-name>
  redis-host: "<REDIS_HOST>"

  # DigitalOcean Managed Redis port (TLS-enabled port)
  # Default: 25061 (DO Managed Redis always uses TLS on this port)
  redis-port: "25061"

  # Redis password (generated by DigitalOcean)
  # Get from: doctl databases connection <cluster-name>
  # CRITICAL: Treat as highly sensitive, rotate every 90 days
  redis-password: "<REDIS_PASSWORD>"

  # TLS enabled flag (always "true" for DO Managed Redis)
  redis-tls: "true"

  # Optional: TLS CA certificate (usually not needed for DO Managed Redis)
  # DO uses publicly trusted certificates
  # Uncomment if custom validation is required:
  # ca-cert: |
  #   -----BEGIN CERTIFICATE-----
  #   ...
  #   -----END CERTIFICATE-----

  # Optional: Redis username (default: "default" for DO Managed Redis)
  # Uncomment if using Redis ACL with custom users:
  # redis-username: "default"

  # Optional: Redis database number (default: 0)
  # Uncomment if using non-default database:
  # redis-db: "0"

---
# Example values for testing (DO NOT USE IN PRODUCTION)
# apiVersion: v1
# kind: Secret
# metadata:
#   name: redis-credentials-test
#   namespace: default
# type: Opaque
# stringData:
#   redis-host: "localhost"
#   redis-port: "6379"
#   redis-password: "test-password"
#   redis-tls: "false"  # Local Redis without TLS
