# Kubernetes Secret for Redpanda Cloud Credentials
# Phase 5 Component 4: Cloud Deployment
#
# IMPORTANT: This file contains placeholders for sensitive credentials.
# DO NOT commit actual credentials to version control.
#
# Usage:
#   1. Replace <PLACEHOLDER> values with actual Redpanda Cloud credentials
#   2. Apply to cluster: kubectl apply -f redpanda-secret.yaml
#   3. Delete this file after applying (or use sealed-secrets for GitOps)
#
# Alternative (recommended): Create secret directly via kubectl
#   kubectl create secret generic redpanda-credentials \
#     --from-literal=brokers="seed-abc123.us-east-1.aws.redpanda.cloud:9092" \
#     --from-literal=sasl-username="todo-app-user" \
#     --from-literal=sasl-password="<generated-password>" \
#     --namespace default

apiVersion: v1
kind: Secret
metadata:
  name: redpanda-credentials
  namespace: default
  labels:
    app: todo-app
    component: messaging
    environment: production
type: Opaque
stringData:
  # Redpanda Cloud broker URLs (comma-separated if multiple)
  # Format: seed-<cluster-id>.<region>.<provider>.redpanda.cloud:9092
  # Example: seed-abc123.us-east-1.aws.redpanda.cloud:9092
  brokers: "<REDPANDA_BROKER_URL>"

  # SASL/SCRAM-SHA-256 username
  # Created via: rpk cloud cluster user create todo-app-user --mechanism SCRAM-SHA-256
  sasl-username: "<REDPANDA_SASL_USERNAME>"

  # SASL/SCRAM-SHA-256 password (32-character generated password)
  # CRITICAL: Treat as highly sensitive, rotate every 90 days
  sasl-password: "<REDPANDA_SASL_PASSWORD>"

  # Optional: TLS CA certificate (if using custom CA)
  # Redpanda Cloud uses public CA, so this is typically not needed
  # Uncomment if custom CA is required:
  # ca-cert: |
  #   -----BEGIN CERTIFICATE-----
  #   MIIDdzCCAl+gAwIBAgIEAgAAuTANBgkqhkiG9w0BAQUFADBaMQswCQYDVQQGEwJJ
  #   ...
  #   -----END CERTIFICATE-----

---
# Example values for testing (DO NOT USE IN PRODUCTION)
# apiVersion: v1
# kind: Secret
# metadata:
#   name: redpanda-credentials-test
#   namespace: default
# type: Opaque
# stringData:
#   brokers: "localhost:9092"  # Local Kafka for testing
#   sasl-username: "test-user"
#   sasl-password: "test-password"
