apiVersion: cluster.redpanda.com/v1alpha1
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: "vectorized/redpanda"
  version: "v23.2.1"
  replicas: 3
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  storage:
    capacity: 50Gi
    storageClassName: "standard"  # Adjust based on cloud provider
  configuration:
    rpcServer:
      port: 33145
    kafkaApi:
      - port: 9092
    pandaproxyApi:
      - port: 8082
    schemaRegistry:
      port: 8081
    adminApi:
      - port: 9644
    developerMode: false  # Production mode
  kafkaEnableAuthorization: false
  superUsers: []
  # Production settings
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "redpanda"
      effect: "NoSchedule"
