apiVersion: v1
kind: Namespace
metadata:
  name: redpanda-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redpanda-operator
  namespace: redpanda-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redpanda-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - cluster.redpanda.com
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redpanda-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redpanda-operator
subjects:
  - kind: ServiceAccount
    name: redpanda-operator
    namespace: redpanda-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-operator
  namespace: redpanda-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redpanda-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redpanda-operator
    spec:
      serviceAccountName: redpanda-operator
      containers:
        - name: operator
          image: vectorized/redpanda-operator:v23.2.1
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "redpanda-operator"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
