apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  # Kafka broker addresses (Minikube-compatible)
  - name: brokers
    value: "kafka-service:9092"

  # Consumer group for topic subscriptions
  - name: consumerGroup
    value: "todo-app-group"

  # Client ID for Kafka connections
  - name: clientID
    value: "todo-app-client"

  # Authentication type (none for local development)
  - name: authType
    value: "none"

  # Maximum message bytes (10 MB)
  - name: maxMessageBytes
    value: "10485760"

  # Consumer configuration
  - name: consumeRetryEnabled
    value: "true"
  - name: consumeRetryInterval
    value: "3s"
  - name: consumeRetryDuration
    value: "30s"

  # Topic auto-creation (useful for development)
  - name: autoOffsetReset
    value: "earliest"

  # Version of Kafka protocol
  - name: version
    value: "2.8.0"

  # Enable idempotent producer for exactly-once semantics
  - name: enableIdempotence
    value: "true"

  # Message compression (gzip for better network efficiency)
  - name: compressionType
    value: "gzip"

  # Timeout for producer sends
  - name: producerMaxWaitTime
    value: "10s"

  # Number of retries for failed messages
  - name: producerRetries
    value: "3"

# Scopes define which apps can use this component
scopes:
- backend-service
- recurring-task-service
- notification-service
